import 'dotenv/config';
import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json({ limit: '2mb' }));

app.get('/api/health', (_req, res) => {
  res.json({ ok: true, app: 'Indo-Backend' });
});

// Backend validation rules used by account creation.
app.post('/api/account/validate-user-id', (req, res) => {
  const userId = String(req.body?.userId || '').trim();
  if (!userId) return res.status(400).json({ ok: false, error: 'User ID is required.' });
  if (userId.length < 1 || userId.length > 50) return res.status(400).json({ ok: false, error: 'User ID must be 1–50 characters.' });
  return res.json({ ok: true, userId });
});

// Indo ID is always generated by Indo and always uses numbers after INDO-.
// The persistent counter will be connected to Firebase Admin in the next backend step.
app.post('/api/account/generate-indo-id', (_req, res) => {
  const number = Date.now().toString().slice(-8);
  res.json({ ok: true, indoId: `INDO-${number}` });
});

app.get('/', (_req, res) => {
  res.json({ app: 'Indo-Backend', status: 'running' });
});

app.listen(PORT, () => {
  console.log(`Indo backend running on port ${PORT}`);
});
